# TYPO3 Extension Manager dump 1.1
#
# Host: localhost    Database: stehlik_t3trunk
#--------------------------------------------------------


#
# Table structure for table "tx_mediaoembed_provider"
#
DROP TABLE IF EXISTS tx_mediaoembed_provider;
CREATE TABLE tx_mediaoembed_provider (
  uid int(11) unsigned NOT NULL auto_increment,
  pid int(11) unsigned NOT NULL default '0',
  tstamp int(11) unsigned NOT NULL default '0',
  crdate int(11) unsigned NOT NULL default '0',
  cruser_id int(11) unsigned NOT NULL default '0',
  name varchar(50) NOT NULL default '',
  embedly_shortname varchar(255) NOT NULL default '',
  hidden tinyint(3) unsigned NOT NULL default '0',
  deleted tinyint(3) unsigned NOT NULL default '0',
  description text,
  parent_provider int(11) unsigned NOT NULL default '0',
  url_schemes text NOT NULL,
  sorting int(11) unsigned NOT NULL default '0',
  endpoint varchar(255) NOT NULL default '',
  generic_providers text,
  is_generic tinyint(3) unsigned NOT NULL default '0',
  generic_endpoints text,
  use_generic_providers text,
  PRIMARY KEY (uid),
  KEY parent (pid,parent_provider)
);


INSERT INTO tx_mediaoembed_provider VALUES ('1', '0', '1304770636', '1303850462', '0', 'embed.ly', 'embedly', '0', '0', 'One API to Rule them All. The Embedly API allows developers to embed videos, images and rich media from 212 services through one API.', '0', '', '1536', 'http://api.embed.ly/1/oembed', '', '1', NULL, NULL);
INSERT INTO tx_mediaoembed_provider VALUES ('2', '0', '1304769869', '1303850462', '0', 'YouTube', 'youtube', '0', '0', 'YouTube is the world\'s most popular online video community, allowing millions of people to discover, watch and share originally-created videos. YouTube provides a forum for people to connect, inform, and inspire others across the globe and acts as a distribution platform for original content creators and advertisers large and small.', '0', 'http://*youtube.com/watch*\r\nhttp://*.youtube.com/v/*\r\nhttp://youtu.be/*\r\nhttp://*.youtube.com/user/*\r\nhttp://*.youtube.com/*#*/*\r\nhttp://m.youtube.com/watch*\r\nhttp://m.youtube.com/index*\r\nhttp://*.youtube.com/profile*\r\nhttp://*.youtube.com/view_play_list*\r\nhttp://*.youtube.com/playlist*', '768', 'http://www.youtube.com/oembed', '1', '0', NULL, '1,220');
INSERT INTO tx_mediaoembed_provider VALUES ('3', '0', '1303850462', '1303850462', '0', 'Justin.tv', 'justintv', '0', '0', 'Justin.tv is the largest online community for people to broadcast, watch and interact around live video.', '0', 'http://*justin.tv/*\nhttp://*justin.tv/*/b/*\nhttp://*justin.tv/*/w/*', '1280', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('4', '0', '1303850462', '1303850462', '0', 'UStream', 'ustream', '0', '0', 'Ustream is an interactive platform that enables anyone with a camera and an Internet connection to quickly and easily broadcast to an online global audience. In less than two minutes, anyone can become a broadcaster by creating their own channel on Ustream or by broadcasting through their own site.', '0', 'http://www.ustream.tv/recorded/*\nhttp://www.ustream.tv/channel/*\nhttp://www.ustream.tv/*', '1792', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('5', '0', '1304769490', '1303850462', '0', 'Qik', 'qik', '0', '0', 'Qik lets you share your everyday life experiences as it happens with your family and friends - right from your mobile phone.', '0', 'http://qik.com/video/*\r\nhttp://qik.com/*\r\nhttp://qik.ly/*', '2048', 'http://qik.com/api/oembed.{format}', '1', '0', NULL, '1,220');
INSERT INTO tx_mediaoembed_provider VALUES ('6', '0', '1304769506', '1303850462', '0', 'Revision3', 'revision3', '0', '0', 'Revision3 is the leading television network for the internet generation. We create and produce all-original episodic community driven programs watched by a super-committed and passionate fan base. Our hyper-connected audience gets the vast majority of its entertainment, information and social connections through the internet.', '0', 'http://*.revision3.com/*', '2304', 'http://revision3.com/api/oembed/', '1', '0', NULL, '1,220');
INSERT INTO tx_mediaoembed_provider VALUES ('7', '0', '1304768816', '1303850462', '0', 'Daily Motion', 'dailymotion', '0', '0', 'Dailymotion is about finding new ways to see, share and engage your world through the power of online video. You can find - or upload - videos about your interests and hobbies, eyewitness accounts of recent news and distant places, and everything else from the strange to the spectacular.', '0', 'http://*.dailymotion.com/video/*\r\nhttp://*.dailymotion.com/*/video/*\r\nhttp://*.dailymotion.com/*', '2560', 'http://www.dailymotion.com/api/oembed/', '1', '0', NULL, '1,220');
INSERT INTO tx_mediaoembed_provider VALUES ('8', '0', '1304768730', '1303850462', '0', 'College Humor', 'collegehumor', '0', '0', 'CollegeHumor is the #1 comedy site on the internet. We showcase hilarious original videos, articles, contests, and interactive features, as well as pictures and videos submitted by fans like you. Our in-house writing and production team powers CH Originals, which delivers original, TV-quality comedy videos multiple times a week.', '0', 'http://collegehumor.com/video:*\r\nhttp://collegehumor.com/video/*\r\nhttp://*.collegehumor.com/video:*\r\nhttp://www.collegehumor.com/video/*', '2816', '', '1', '0', NULL, '1,220');
INSERT INTO tx_mediaoembed_provider VALUES ('9', '0', '1303850462', '1303850462', '0', 'TwitVid', 'twitvid', '0', '0', 'Twitvid.com is an easy way to stream videos when you tweet.', '0', 'http://*twitvid.com/*', '3072', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('10', '0', '1303850462', '1303850462', '0', 'Break.com', 'break', '0', '0', 'Break.com is the premier online entertainment destination for guys with over 18 million unique viewers and 50 million page impressions per month', '0', 'http://www.break.com/*/*', '3328', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('11', '0', '1303850688', '1303850462', '0', 'Myspace Videos', 'myspacevideos', '0', '0', 'MySpace is a technology company connecting people through personal expression, content, and culture. MySpace empowers its global community to experience the Internet through a social lens by integrating personal profiles, photos, videos, mobile, messaging, games, and the world\'s largest music community.', '0', 'http://vids.myspace.com/index.cfm?fuseaction=vids.individual&videoid*\nhttp://www.myspace.com/index.cfm?fuseaction=*&videoid*', '3584', 'http://lab.viddler.com/services/oembed/', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('12', '0', '1304769271', '1303850462', '0', 'MetaCafe', 'metacafe', '0', '0', 'Metacafe is a social video site that algorithmically filters what appears on the site. Users and content producers are allowed to submit any videos they want but Metacafe uses its filtering algorithm VideoRank to choose the "most entertaining" and "high quality" videos.', '0', 'http://*.metacafe.com/watch/*\r\nhttp://www.metacafe.com/w/*', '3840', '', '1', '0', NULL, '1,220');
INSERT INTO tx_mediaoembed_provider VALUES ('13', '0', '1304768659', '1303850462', '0', 'Blip.tv', 'bliptv', '0', '0', 'More than 48,000 independently produced Web shows use blip.tv to reach more than 22,000,000 people. We distribute more than 2.4 million episodes from these shows across the entire video Internet and onto television screens across the country', '0', 'http://blip.tv/file/*\r\nhttp://*.blip.tv/file/*\r\nhttp://*.blip.tv/*', '4096', 'http://blip.tv/oembed/', '1', '0', NULL, '1,220');
INSERT INTO tx_mediaoembed_provider VALUES ('14', '0', '1304769100', '1303850462', '0', 'Google Videos', 'googlevideo', '0', '0', 'Google Videos is a free video sharing website and also a video search engine from Google Inc. Google Videos allows selected videos to be remotely embedded on other websites and provides the necessary HTML code alongside the media, similar to YouTube.', '0', 'http://video.google.com/videoplay?*', '4352', '', '1', '0', NULL, '1,220');
INSERT INTO tx_mediaoembed_provider VALUES ('15', '0', '1303850462', '1303850462', '0', 'Revver', 'revver', '0', '0', 'Revver is an online media network built the way the internet really works. We support the free and unlimited sharing of media. Our unique technology pairs videos with targeted ads and tracks them as they spread across the web. So no matter where your video travels, you benefit because we share the advertising revenue with you.', '0', 'http://*revver.com/video/*', '4608', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('16', '0', '1303850462', '1303850462', '0', 'Yahoo! Video', 'yahoovideo', '0', '0', 'Yahoo! Video is the best place to view and upload video on the Web. It\'s the perfect pop-culture mashup, the best of the best-all video from across the Yahoo! network in one place. Of course we have unicorns, chipmunks, ninjas, cats, and robots. We also have music videos and news, sports, autos, comedy, TV clips, and movie previews.', '0', 'http://video.yahoo.com/watch/*/*\nhttp://video.yahoo.com/network/*', '4864', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('17', '0', '1304769662', '1303850462', '0', 'Viddler', 'viddler', '0', '0', 'A fresh, creative web application that allows you to upload, enhance, and share digital video easily and quickly inside your web browser.', '0', 'http://*.viddler.com/*\r\nhttp://*viddler.com/explore/*/videos/*\r\nhttp://*.viddler.com/explore/*', '5120', 'http://lab.viddler.com/services/oembed/', '1', '0', NULL, '1,220');
INSERT INTO tx_mediaoembed_provider VALUES ('18', '0', '1303850462', '1303850462', '0', 'LiveLeak', 'liveleak', '0', '0', 'LiveLeak is a video sharing website that lets users post and share videos. LiveLeak places emphasis on current events, politics and reality-based footage such as war scenes from various parts of the world.', '0', 'http://liveleak.com/view?*\nhttp://www.liveleak.com/view?*', '5376', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('19', '0', '1303850462', '1303850462', '0', 'Animoto', 'animoto', '0', '0', 'Animoto automatically produces beautifully orchestrated, completely unique video pieces from your photos, video clips and music.', '0', 'http://animoto.com/play/*', '5632', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('20', '0', '1304768856', '1303850462', '0', 'dotSUB', 'dotsub', '0', '0', 'dotSUB is a browser based, one-stop, self contained system for creating and viewing subtitles for videos in multiple languages across all platforms, including web based, mobile devices, and transcription and video editing systems.', '0', 'http://dotsub.com/view/*', '5888', 'http://dotsub.com/services/oembed', '1', '0', NULL, '1,220');
INSERT INTO tx_mediaoembed_provider VALUES ('21', '0', '1303850462', '1303850462', '0', 'Overstream', 'overstream', '0', '0', 'Have you ever wanted to customize an online video by adding your own comments or subtitles in any language, or wanted to send a custom video postcard? All of this is possible with Overstream: using the online Overstream Editor, you can easily create and synchronize your subtitles to any online video*, store them on the Overstream server, and send the link to the subtitled video overstream to your friends.', '0', 'http://www.overstream.net/view.php?oid=*', '6144', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('22', '0', '1303850462', '1303850462', '0', 'Livestream', 'livestream', '0', '0', 'Watch live streaming video and chat online, or broadcast your own events in minutes.', '0', 'http://www.livestream.com/*', '6400', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('23', '0', '1303850462', '1303850462', '0', 'WorldStarHipHop', 'worldstarhiphop', '0', '0', 'WorldStarHipHop contains videos about show, hip hop and entertainment.', '0', 'http://www.worldstarhiphop.com/videos/video*.php?v=*\nhttp://worldstarhiphop.com/videos/video*.php?v=*', '6656', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('24', '0', '1303850462', '1303850462', '0', 'TeacherTube', 'teachertube', '0', '0', 'Our goal at TeacherTube.com is to provide an online community for sharing instructional teacher videos. Upload your lesson plan videos or watch student video lessons at our website.', '0', 'http://teachertube.com/viewVideo.php*\nhttp://www.teachertube.com/viewVideo.php*\nhttp://www1.teachertube.com/viewVideo.php*\nhttp://www2.teachertube.com/viewVideo.php*', '6912', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('25', '0', '1303850462', '1303850462', '0', 'Bambuser', 'bambuser', '0', '0', 'Live video streaming from your mobile phone or webcam.', '0', 'http://bambuser.com/v/*\nhttp://bambuser.com/channel/*\nhttp://bambuser.com/channel/*/broadcast/*', '7168', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('26', '0', '1303850462', '1303850462', '0', 'SchoolTube', 'schooltube', '0', '0', 'SchoolTube.com is the nation\'s largest K-12 moderated video sharing website that provides students and educators with a safe and FREE video sharing website that is exclusively endorsed by leading education associations.', '0', 'http://www.schooltube.com/video/*/*', '7424', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('27', '0', '1303850462', '1303850462', '0', 'Big Think', 'bigthink', '0', '0', 'Big Think is a global forum connecting people and ideas.', '0', 'http://bigthink.com/ideas/*\nhttp://bigthink.com/series/*', '7680', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('28', '0', '1303850462', '1303850462', '0', 'JibJab', 'jibjab', '0', '0', 'JibJab is an online entertainment studio dedicated to making things that make people laugh. You can create personalized "Starring You" videos on our website, send ecards to friends on special occasions and watch original videos.', '0', 'http://sendables.jibjab.com/view/*\nhttp://sendables.jibjab.com/originals/*', '7936', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('29', '0', '1303850462', '1303850462', '0', 'xtranormal', 'xtranormal', '0', '0', 'xtranormal\'s mission is to bring movie-making to the people.', '0', 'http://www.xtranormal.com/watch/*', '8192', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('30', '0', '1303850462', '1303850462', '0', 'Socialcam', 'socialcam', '0', '0', 'The easiest way to share videos with friends.', '0', 'http://socialcam.com/v/*\nhttp://www.socialcam.com/v/*', '8448', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('31', '0', '1303850463', '1303850463', '0', 'Dipdive', 'dipdive', '0', '0', 'Dipdive is a Lifestyle Engine for Music, Arts, Action and More', '0', 'http://dipdive.com/media/*\nhttp://dipdive.com/member/*/media/*\nhttp://dipdive.com/v/*\nhttp://*.dipdive.com/media/*\nhttp://*.dipdive.com/v/*', '8704', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('32', '0', '1303850463', '1303850463', '0', 'Youku', 'youku', '0', '0', 'China\'s first video website, Youku features "quick play, quick release, quick search for" all news, video and sports.', '0', 'http://v.youku.com/v_show/*.html\nhttp://v.youku.com/v_playlist/*.html', '8960', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('33', '0', '1303850463', '1303850463', '0', 'snotr', 'snotr', '0', '0', 'Snotr is a source for short and funny or interesting video.', '0', 'http://www.snotr.com/video/*\nhttp://snotr.com/video/*', '9216', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('34', '0', '1303850463', '1303850463', '0', 'Jardenberg', 'jardenberg', '0', '0', 'Video Service for Joakim Jardenberg, Popular Swedish Digital Blogger.', '0', 'http://video.jardenberg.se/*', '9472', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('35', '0', '1303850463', '1303850463', '0', 'Clipfish', 'clipfish', '0', '0', 'Clipfish.de offers a wide variety of cutting-edge video from the TV, music, comedy, movies, games, and news and lifestyle', '0', 'http://www.clipfish.de/*/*/video/*', '9728', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('36', '0', '1303850463', '1303850463', '0', 'MyVideo', 'myvideo', '0', '0', 'At MyVideo you can find the best free videos and clips.', '0', 'http://www.myvideo.de/watch/*', '9984', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('37', '0', '1303850463', '1303850463', '0', 'The White House', 'whitehouse', '0', '0', 'WhiteHouse.gov is the official web site for the White House and President Barack Obama, the 44th President of the United States.', '0', 'http://www.whitehouse.gov/photos-and-video/video/*\nhttp://www.whitehouse.gov/video/*\nhttp://wh.gov/photos-and-video/video/*\nhttp://wh.gov/video/*', '10240', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('38', '0', '1304769189', '1303850463', '0', 'Hulu', 'hulu', '0', '0', 'Hulu is an online video service that offers hit TV shows, movies and clips at Hulu.com and other online destination sites - anytime in the U.S.', '0', 'http://www.hulu.com/watch*\r\nhttp://www.hulu.com/w/*\r\nhttp://hulu.com/watch*\r\nhttp://hulu.com/w/*', '10496', 'http://www.hulu.com/api/oembed.{format}', '1', '0', NULL, '1,220');
INSERT INTO tx_mediaoembed_provider VALUES ('39', '0', '1303850463', '1303850463', '0', 'Crackle', 'crackle', '0', '0', 'Crackle, Inc., a Sony Pictures Entertainment Company, is a multi-platform next-generation video entertainment network that distributes digital content including original short form series and full-length traditional programming from Sony Pictures\' vast library of television series and feature films. ', '0', 'http://*crackle.com/c/*', '10752', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('40', '0', '1303850463', '1303850463', '0', 'Fancast', 'fancast', '0', '0', 'Fancast is THE top entertainment site dedicated to celebrating television. Fancast gives fans instant access to an extensive video collection of television shows, movies, trailers and clips, so they can tune-in, catch-up and critique their favorite television programming.', '0', 'http://www.fancast.com/*/videos', '11008', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('41', '0', '1304769123', '1303850463', '0', 'Funny or Die', 'funnyordie', '0', '0', 'Funny Or Die is a comedy video website that combines user generated content with original, exclusive content. The site is a place where celebrities, established and up-and-coming comedians and regular users can all put up stuff they think is funny.', '0', 'http://*.funnyordie.com/videos/*\r\nhttp://www.funnyordie.com/m/*\r\nhttp://funnyordie.com/videos/*\r\nhttp://funnyordie.com/m/*', '11264', '', '1', '0', NULL, '1,220');
INSERT INTO tx_mediaoembed_provider VALUES ('42', '0', '1304769700', '1303850463', '0', 'Vimeo', 'vimeo', '0', '0', 'Vimeo is a cleanly-designed video sharing website that allows people to publish their videos for public consumption or just for friends and family.', '0', 'http://www.vimeo.com/groups/*/videos/*\r\nhttp://www.vimeo.com/groups/*/*\r\nhttp://www.vimeo.com/*\r\nhttp://vimeo.com/groups/*/videos/*\r\nhttp://vimeo.com/*\r\nhttp://vimeo.com/m/#/*', '11520', 'http://www.vimeo.com/api/oembed.{format}', '1', '0', NULL, '1,220');
INSERT INTO tx_mediaoembed_provider VALUES ('43', '0', '1303850463', '1303850463', '0', 'TED', 'ted', '0', '0', 'TED is a small nonprofit devoted to Ideas Worth Spreading. It started out (in 1984) as a conference bringing together people from three worlds:  Technology, Entertainment, Design.', '0', 'http://www.ted.com/talks/*.html*\nhttp://www.ted.com/talks/lang/*/*.html*\nhttp://www.ted.com/index.php/talks/*.html*\nhttp://www.ted.com/index.php/talks/lang/*/*.html*', '11776', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('44', '0', '1304769343', '1303850463', '0', 'NFB', 'nfb', '0', '0', 'The National Film Board of Canada (or simply National Film Board or NFB) is Canada\'s public film producer and distributor. An agency of the Government of Canada, the NFB produces and distributes innovative, socially relevant documentary, animation, alternative drama and digital media productions. ', '0', 'http://*nfb.ca/film/*', '12032', '', '1', '0', NULL, '1,220');
INSERT INTO tx_mediaoembed_provider VALUES ('45', '0', '1304768769', '1303850463', '0', 'The Daily Show', 'thedailyshow', '0', '0', 'The Daily Show is an Emmy and Peabody Award-winning program that takes a reality-based look at news, trends, pop culture, current events, politics, sports and entertainment with an alternative point of view. In each show, anchorman Jon Stewart and a team of correspondents, including Aasif Mandvi, Wyatt Cenac, John Oliver, Jason Jones and Samantha Bee, comment on the day\'s stories, employing actual news footage, taped field pieces, in-studio guests and on-the-spot coverage of important news events.', '0', 'http://www.thedailyshow.com/watch/*\r\nhttp://www.thedailyshow.com/full-episodes/*\r\nhttp://www.thedailyshow.com/collection/*/*/*\r\nhttp://*.thedailyshow.com/video/*', '12288', '', '1', '0', NULL, '1,220');
INSERT INTO tx_mediaoembed_provider VALUES ('46', '0', '1303850463', '1303850463', '0', 'Yahoo! Movies', 'yahoomovies', '0', '0', 'Yahoo! Movies is your guide to everything about movies online, from upcoming releases, to movies in theaters and movies on DVD. Find trailers and clips, movie news, cast & credits, celebrity photos, movie showtimes & tickets, box office reports and much more!', '0', 'http://movies.yahoo.com/movie/*/video/*\nhttp://movies.yahoo.com/movie/*/trailer\nhttp://movies.yahoo.com/movie/*/video', '12544', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('47', '0', '1303850463', '1303850463', '0', 'Colbert Nation', 'colbertnation', '0', '0', 'Feel the news along with Stephen Colbert, America\'s ballsiest pundit, with highlights and full episodes of The Colbert Report.', '0', 'http://www.colbertnation.com/the-colbert-report-collections/*\nhttp://www.colbertnation.com/full-episodes/*\nhttp://www.colbertnation.com/the-colbert-report-videos/*', '12800', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('48', '0', '1303850463', '1303850463', '0', 'Comedy Central', 'comedycentral', '0', '0', 'Your Source for Comedians, Funny Video, TV Shows, Games, Jokes & Ringtones.', '0', 'http://www.comedycentral.com/videos/index.jhtml?*', '13056', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('49', '0', '1303850463', '1303850463', '0', 'The Onion', 'theonion', '0', '0', 'The Onion is an American news satire organization. It features satirical articles reporting on international, national, and local news as well as an entertainment newspaper and website known as The A.V. Club. It claims a national print circulation of 690,000 and says 61 percent of its web site readers are between 18 and 44 years old.', '0', 'http://www.theonion.com/video/*\nhttp://theonion.com/video/*', '13312', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('50', '0', '1303850463', '1303850463', '0', 'WordPress TV', 'wordpresstv', '0', '0', 'WordPress.tv is Your Visual Resource for All Things WordPress', '0', 'http://wordpress.tv/*/*/*/*/', '13568', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('51', '0', '1303850463', '1303850463', '0', 'Trailer Addict', 'traileraddict', '0', '0', 'TrailerAddict was created for those who understand what it means to be a fan of movie trailers. Getting to the theater early on purpose, we are bound by the knowledge that trailers are (at times) better than the films they represent. TrailerAddict has been built not for those who like a good trailer now and then, but those who understand that the need to watch trailers is a state of mind.', '0', 'http://www.traileraddict.com/trailer/*\nhttp://www.traileraddict.com/clip/*\nhttp://www.traileraddict.com/poster/*', '13824', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('52', '0', '1303850463', '1303850463', '0', 'The Escapist', 'escapistmagazine', '0', '0', 'The Escapist is a leading video gaming destination offering video game enthusiasts high-quality, innovative and exclusive content with a considered approach to its audience.', '0', 'http://www.escapistmagazine.com/videos/*', '14080', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('53', '0', '1303850463', '1303850463', '0', 'TrailerSpy', 'trailerspy', '0', '0', 'At TrailerSpy, our goal isn\'t necessarily to be the most popular trailer site on the web. Our goal is to be the best trailer site on the web. View movie, video game, book and many other trailers at TrailerSpy.', '0', 'http://www.trailerspy.com/trailer/*/*\nhttp://www.trailerspy.com/trailer/*\nhttp://www.trailerspy.com/view_video.php*', '14336', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('54', '0', '1303850463', '1303850463', '0', 'Atom.com', 'atom', '0', '0', 'Atom Entertainment aggregates and distributes the casual games, short films, and animations on the web.', '0', 'http://www.atom.com/*/*/', '14592', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('55', '0', '1303850463', '1303850463', '0', 'FORA.tv', 'foratv', '0', '0', 'FORA.tv helps intelligent, engaged audiences get smart. Our users find, enjoy, and share videos about the people, issues, and ideas changing the world.', '0', 'http://fora.tv/*/*/*/*', '14848', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('56', '0', '1303850463', '1303850463', '0', 'spike.com', 'spike', '0', '0', 'SPIKE.COM: Check out the premier online destination for Men!', '0', 'http://www.spike.com/video/*', '15104', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('57', '0', '1303850463', '1303850463', '0', 'GameTrailers.com', 'gametrailers', '0', '0', '"Watch new video game trailers, read reviews and previews of upcoming video games at GameTrailers.com.', '0', 'http://www.gametrailers.com/video/*\nhttp://gametrailers.com/video/*', '15360', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('58', '0', '1303850463', '1303850463', '0', 'Koldcast Tv', 'koldcasttv', '0', '0', 'KoldCast TV, where the future of Internet-served television is taking shape. And where a new form of entertainment is incubated, featured, and introduced in new ways.', '0', 'http://www.koldcast.tv/video/*\nhttp://www.koldcast.tv/#video:*', '15616', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('59', '0', '1303850463', '1303850463', '0', 'TechCrunch TV', 'techcrunchtv', '0', '0', 'TechCrunch was founded on June 11, 2005, as a weblog dedicated to obsessively profiling and reviewing new Internet products and companies.', '0', 'http://techcrunch.tv/watch*\nhttp://techcrunch.tv/*/watch*', '15872', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('60', '0', '1303850463', '1303850463', '0', 'Mixergy', 'mixergy', '0', '0', 'Mixergy is where the ambitious learn from a mix of experienced mentors.', '0', 'http://mixergy.com/*', '16128', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('61', '0', '1303850463', '1303850463', '0', 'PBS Video', 'pbsvideo', '0', '0', 'On PBS Video, award-winning national programming and locally produced shows are just a click away. Watch your favorite shows and catch the episodes you may have missed, all on your schedule.', '0', 'http://video.pbs.org/video/*', '16384', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('62', '0', '1303850463', '1303850463', '0', 'Zapiks', 'zapiks', '0', '0', 'Since 1996, the best action sport videos on the Web! on now on your phone!', '0', 'http://www.zapiks.com/*', '16640', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('63', '0', '1303850463', '1303850463', '0', 'Digg', 'digg', '0', '0', 'A place for people to discover and share content from anywhere on the web.', '0', 'http://tv.digg.com/diggnation/*\nhttp://tv.digg.com/diggreel/*\nhttp://tv.digg.com/diggdialogg/*', '16896', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('64', '0', '1303850463', '1303850463', '0', 'TruTv', 'trutv', '0', '0', 'truTV is television\'s destination for real-life stories told from an exciting and dramatic first-person perspective and features high-stakes, action-packed originals that give viewers access to places and situations they can\'t normally experience.', '0', 'http://www.trutv.com/video/*', '17152', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('65', '0', '1303850463', '1303850463', '0', 'NZ On Screen', 'nzonscreen', '0', '0', 'NZ On Screen is an online showcase of archival New Zealand television and film.', '0', 'http://www.nzonscreen.com/title/*\nhttp://nzonscreen.com/title/*', '17408', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('66', '0', '1303850463', '1303850463', '0', 'Wistia', 'wistia', '0', '0', 'Wistia Video Platform allows you to host, share and track video.', '0', 'http://app.wistia.com/embed/medias/*\nhttps://app.wistia.com/embed/medias/*', '17664', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('67', '0', '1303850463', '1303850463', '0', 'Hungry Nation', 'hungrynation', '0', '0', 'Hungry Nation celebrates real food, real people, with shows that are more about food appreciation and inspiration than complicated recipes, expensive ingredients or star chefs.', '0', 'http://hungrynation.tv/*/episode/*\nhttp://www.hungrynation.tv/*/episode/*\nhttp://hungrynation.tv/episode/*\nhttp://www.hungrynation.tv/episode/*', '17920', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('68', '0', '1303850463', '1303850463', '0', 'Indy Mogul', 'indymogul', '0', '0', 'Indy Mogul is leading the next generation of filmmakers to take over Hollywood, one blood-squirting fake ax at a time.', '0', 'http://indymogul.com/*/episode/*\nhttp://www.indymogul.com/*/episode/*\nhttp://indymogul.com/episode/*\nhttp://www.indymogul.com/episode/*', '18176', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('69', '0', '1303850463', '1303850463', '0', 'Channel Frederator', 'channelfrederator', '0', '0', 'Channel Frederator isn\'t just another place for animation on the web. It is the home for animation fans on the web, where the cartoon tribe can meet, show their work, and connect with each other.', '0', 'http://channelfrederator.com/*/episode/*\nhttp://www.channelfrederator.com/*/episode/*\nhttp://channelfrederator.com/episode/*\nhttp://www.channelfrederator.com/episode/*', '18432', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('70', '0', '1303850463', '1303850463', '0', 'TMI Weekly', 'tmiweekly', '0', '0', 'TMI Weekly is a web-paced talk that taps into pop culture conversation and highlight topics important to their audience: professional young women who live their lives both online and offline.', '0', 'http://tmiweekly.com/*/episode/*\nhttp://www.tmiweekly.com/*/episode/*\nhttp://tmiweekly.com/episode/*\nhttp://www.tmiweekly.com/episode/*', '18688', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('71', '0', '1303850463', '1303850463', '0', '$99 Music Videos', '99dollarmusicvideos', '0', '0', '$99 Music Videos is a critical smash that brings together cutting-edge music bands and musicians with up-and-coming filmmakers and exposes their collaboration to a whole new wave of online fans.', '0', 'http://99dollarmusicvideos.com/*/episode/*\nhttp://www.99dollarmusicvideos.com/*/episode/*\nhttp://99dollarmusicvideos.com/episode/*\nhttp://www.99dollarmusicvideos.com/episode/*', '18944', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('72', '0', '1303850463', '1303850463', '0', 'Ultra Kawaii', 'ultrakawaii', '0', '0', 'Ultra Kawaii showcases the cutest pet and animal videos submitted by viewers from around the world.', '0', 'http://ultrakawaii.com/*/episode/*\nhttp://www.ultrakawaii.com/*/episode/*\nhttp://ultrakawaii.com/episode/*\nhttp://www.ultrakawaii.com/episode/*', '19200', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('73', '0', '1303850463', '1303850463', '0', 'Barely Political', 'barelypolitical', '0', '0', 'Barely Political produces some of the most relevant, popular, and blogged-about videos on the Internet.', '0', 'http://barelypolitical.com/*/episode/*\nhttp://www.barelypolitical.com/*/episode/*\nhttp://barelypolitical.com/episode/*\nhttp://www.barelypolitical.com/episode/*', '19456', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('74', '0', '1303850463', '1303850463', '0', 'Barely Digital', 'barelydigital', '0', '0', 'Barely Digital features sketch comedy and music video parodies to satirize the worlds of gaming, social networks, gadgets, the Internet-at-large and much more.', '0', 'http://barelydigital.com/*/episode/*\nhttp://www.barelydigital.com/*/episode/*\nhttp://barelydigital.com/episode/*\nhttp://www.barelydigital.com/episode/*', '19712', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('75', '0', '1303850463', '1303850463', '0', 'ThreadBanger', 'threadbanger', '0', '0', 'ThreadBanger is the first network dedicated to do-it-yourself fashion ideas, tips, and advice for people of all ages and experience levels', '0', 'http://threadbanger.com/*/episode/*\nhttp://www.threadbanger.com/*/episode/*\nhttp://threadbanger.com/episode/*\nhttp://www.threadbanger.com/episode/*', '19968', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('76', '0', '1303850463', '1303850463', '0', 'VOD Cars', 'vodcars', '0', '0', 'VOD Cars takes the videos that the world shoots, edits and submits to us and then packages them into episodes of pure automotive entertainment.', '0', 'http://vodcars.com/*/episode/*\nhttp://www.vodcars.com/*/episode/*\nhttp://vodcars.com/episode/*\nhttp://www.vodcars.com/episode/*', '20224', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('77', '0', '1303850463', '1303850463', '0', 'Confreaks', 'confreaks', '0', '0', 'Expert recording services for conferences, seminars, and workshops.', '0', 'http://confreaks.net/videos/*\nhttp://www.confreaks.net/videos/*', '20480', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('78', '0', '1303850463', '1303850463', '0', 'All Things Digital', 'allthingsd', '0', '0', 'News, analysis and opinion about the digital revolution.', '0', 'http://video.allthingsd.com/video/*', '20736', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('79', '0', '1303850463', '1303850463', '0', 'New York Magazine', 'nymag', '0', '0', 'Find and share videos at New York Magazine.', '0', 'http://videos.nymag.com/*', '20992', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('80', '0', '1303850463', '1303850463', '0', 'Aniboom', 'aniboom', '0', '0', 'The virtual animation studio.', '0', 'http://aniboom.com/animation-video/*\nhttp://www.aniboom.com/animation-video/*', '21248', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('81', '0', '1303850463', '1303850463', '0', 'ClipShack', 'clipshack', '0', '0', 'ClipShack is a community for videophiles; a destination where people can post their video for general public viewing and comment.', '0', 'http://clipshack.com/Clip.aspx?*\nhttp://www.clipshack.com/Clip.aspx?*', '21504', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('82', '0', '1303850463', '1303850463', '0', 'GrindTV', 'grindtv', '0', '0', 'GrindTV.com is the world\'s leading destination for action sports videos, pictures and information about the skate, surf, snow, and moto lifestyle.', '0', 'http://grindtv.com/*/video/*\nhttp://www.grindtv.com/*/video/*', '21760', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('83', '0', '1303850463', '1303850463', '0', 'ifood.tv', 'ifoodtv', '0', '0', 'ifood.tv is a place to make friends, chat about food, learn about cooking traditions and satisfy your culinary curiosity.', '0', 'http://ifood.tv/recipe/*\nhttp://ifood.tv/video/*\nhttp://ifood.tv/channel/user/*\nhttp://www.ifood.tv/recipe/*\nhttp://www.ifood.tv/video/*\nhttp://www.ifood.tv/channel/user/*', '22016', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('84', '0', '1303850463', '1303850463', '0', 'Logo: Fierce TV', 'logotv', '0', '0', 'Watch Logo reality TV shows like RuPaul\'s Drag Race and The A-List: New York, free full episodes online.', '0', 'http://logotv.com/video/*\nhttp://www.logotv.com/video/*', '22272', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('85', '0', '1303850463', '1303850463', '0', 'Lonely Planet', 'lonelyplanet', '0', '0', 'Travel guides and guidebooks. Travel advice, tips and destination information to inspire you from Lonely Planet.', '0', 'http://lonelyplanet.com/Clip.aspx?*\nhttp://www.lonelyplanet.com/Clip.aspx?*', '22528', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('86', '0', '1303850463', '1303850463', '0', 'Street Fire', 'streetfire', '0', '0', 'StreetFire.net is the first and largest user generated video sharing service that specifically caters to car, truck and motorcycle enthusiasts.', '0', 'http://streetfire.net/video/*.htm*\nhttp://www.streetfire.net/video/*.htm*', '22784', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('87', '0', '1303850463', '1303850463', '0', 'TroopTube', 'trooptube', '0', '0', 'TroopTube is the new online video site designed to help military families connect and keep in touch while miles apart.', '0', 'http://trooptube.tv/videos/*\nhttp://www.trooptube.tv/videos/*', '23040', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('88', '0', '1303850463', '1303850463', '0', 'ScienceStage', 'sciencestage', '0', '0', 'ScienceStage.com is a virtual conference room, lecture hall, laboratory, library and meeting venue all in one.', '0', 'http://sciencestage.com/v/*.html\nhttp://sciencestage.com/a/*.html\nhttp://www.sciencestage.com/v/*.html\nhttp://www.sciencestage.com/a/*.html', '23296', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('89', '0', '1303850463', '1303850463', '0', 'GodTube', 'godtube', '0', '0', 'Christian Videos', '0', 'http://www.godtube.com/featured/video/*\nhttp://godtube.com/featured/video/*\nhttp://www.godtube.com/watch/*\nhttp://godtube.com/watch/*', '23552', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('90', '0', '1303850463', '1303850463', '0', 'Tangle', 'tangle', '0', '0', 'Tangle is a global technology company that creates social networking tools for the faith-based and family friendly marketplace.', '0', 'http://www.tangle.com/view_video*', '23808', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('91', '0', '1303850463', '1303850463', '0', 'Media Matters', 'mediamatters', '0', '0', 'Media Matters for America is a Web-based, not-for-profit, 501(c)(3) progressive research and information center dedicated to comprehensively monitoring, analyzing, and correcting conservative misinformation in the U.S. media.', '0', 'http://mediamatters.org/mmtv/*', '24064', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('92', '0', '1304768690', '1303850463', '0', 'Clikthrough', 'clikthrough', '0', '0', 'Clikthrough has created the technology that makes online video interactive within an online theater viewing experience.', '0', 'http://*.clikthrough.com/theater/video/*', '24320', 'http://clikthrough.com/services/oembed', '1', '0', NULL, '1,220');
INSERT INTO tx_mediaoembed_provider VALUES ('93', '0', '1303850463', '1303850463', '0', 'GitHub', 'github', '0', '0', 'GitHub is the best way to participate in that collaboration: fork projects, send pull requests, create issues, and monitor development with all of your public and private code.', '0', 'http://gist.github.com/*', '24576', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('94', '0', '1304769638', '1303850463', '0', 'Twitter', 'twitter', '0', '0', 'Twitter is a real&#45;time information network powered by people all around the world that lets you share and discover what\'s happening now.', '0', 'http://twitter.com/*/status/*\r\nhttp://twitter.com/*/statuses/*\r\nhttp://www.twitter.com/*/status/*\r\nhttp://www.twitter.com/*/statuses/*\r\nhttp://mobile.twitter.com/*/status/*\r\nhttp://mobile.twitter.com/*/statuses/*\r\nhttps://twitter.com/*/status/*\r\nhttps://twitter.com/*/statuses/*\r\nhttps://www.twitter.com/*/status/*\r\nhttps://www.twitter.com/*/statuses/*\r\nhttps://mobile.twitter.com/*/status/*\r\nhttps://mobile.twitter.com/*/statuses/*', '24832', '', '1', '0', NULL, '1,220');
INSERT INTO tx_mediaoembed_provider VALUES ('95', '0', '1303850463', '1303850463', '0', 'CrunchBase', 'crunchbase', '0', '0', 'CrunchBase is the free directory of technology companies, people, and investors that anyone can edit. Developed and Maintained by TechCrunch.', '0', 'http://www.crunchbase.com/*/*\nhttp://crunchbase.com/*/*', '25088', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('96', '0', '1304769567', '1303850463', '0', 'SlideShare', 'slideshare', '0', '0', 'SlideShare is a community for sharing presentations. Individuals or organizations can upload and share PowerPoint, PDF, or OpenOffice presentations. Anyone can find presentations on their topic of interest.', '0', 'http://www.slideshare.net/*/*\r\nhttp://www.slideshare.net/mobile/*/*\r\nhttp://slidesha.re/*\r\nhttp://*.slideshare.net/*', '25344', '', '1', '0', NULL, '1,220');
INSERT INTO tx_mediaoembed_provider VALUES ('97', '0', '1304769540', '1303850463', '0', 'Scribd', 'scribd', '0', '0', 'Scribd is the largest social publishing company in the world, the Website where tens of millions of people each month publish and discover original writings and documents.', '0', 'http://scribd.com/doc/*\r\nhttp://www.scribd.com/doc/*\r\nhttp://scribd.com/mobile/documents/*\r\nhttp://www.scribd.com/mobile/documents/*\r\nhttp://*.scribd.com/*', '25600', 'http://www.scribd.com/services/oembed', '1', '0', NULL, '1,220');
INSERT INTO tx_mediaoembed_provider VALUES ('98', '0', '1303850463', '1303850463', '0', 'Screenr', 'screenr', '0', '0', 'Screenr allows you to make screencasts for your followers on Twitter as easily as you tweet. Just record, and a ready-to-tweet screencast is instantly created.', '0', 'http://screenr.com/*', '25856', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('99', '0', '1303850463', '1303850463', '0', 'PollDaddy', 'polldaddy', '0', '0', 'Set up an online survey in minutes and start collecting responses in real-time!', '0', 'http://polldaddy.com/community/poll/*\nhttp://polldaddy.com/poll/*\nhttp://answers.polldaddy.com/poll/*', '26112', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('100', '0', '1304768583', '1303850463', '0', '5min', '5min', '0', '0', '5min is the leading syndication platform for broadband instructional, knowledge and lifestyle videos. Our library includes tens of thousands of videos across 20 categories and 140 subcategories, which are professionally produced and brand-safe.', '0', 'http://www.5min.com/Video/*', '26368', '', '1', '0', NULL, '1,220');
INSERT INTO tx_mediaoembed_provider VALUES ('101', '0', '1303850463', '1303850463', '0', 'Howcast', 'howcast', '0', '0', 'Howcast is the best source for fun, free, and useful how-to videos and guides.', '0', 'http://www.howcast.com/videos/*', '26624', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('102', '0', '1303850463', '1303850463', '0', 'Screencast', 'screencast', '0', '0', 'Screencast.com is a TechSmith solution for business and academic professionals looking to manage and share videos, images, documents, or anything else online. Screencast.com\'s high-quality content-hosting gives you complete control over how, when and to whom your content is distributed.', '0', 'http://www.screencast.com/*/media/*\nhttp://screencast.com/*/media/*\nhttp://www.screencast.com/t/*\nhttp://screencast.com/t/*', '26880', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('103', '0', '1304766398', '1303850463', '0', 'Issuu', 'issuu', '0', '0', 'Issuu is the leading digital publishing platform delivering exceptional reading experiences of magazines, books, catalogs, reports, and more.', '0', 'http://issuu.com/*/docs/*', '27136', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('104', '0', '1303850463', '1303850463', '0', 'Kickstarter', 'kickstarter', '0', '0', 'Kickstarter is a new way to fund creative ideas and ambitious endeavors.', '0', 'http://www.kickstarter.com/projects/*/*', '27392', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('105', '0', '1303850463', '1303850463', '0', 'Scrapblog', 'scrapblog', '0', '0', 'With Scrapblog, your photos and videos become the stars of all the stories you want to tell.', '0', 'http://www.scrapblog.com/viewer/viewer.aspx*', '27648', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('106', '0', '1303850463', '1303850463', '0', 'Ping.fm', 'pingfm', '0', '0', 'Ping.fm was created for the sole purpose of making it as easy as possible to share your posts with the world. Now you don\'t have to fumble around the web in order to post anymore, you can just post once, and be done with it.', '0', 'http://ping.fm/p/*', '27904', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('107', '0', '1303850463', '1303850463', '0', 'Chart.ly', 'chartly', '0', '0', 'Chart.ly by StockTwits, is a social charting platform enabling users to discover and share charts, graphs, and videos.', '0', 'http://chart.ly/symbols/*\nhttp://chart.ly/*', '28160', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('108', '0', '1303850463', '1303850463', '0', 'Google Maps', 'googlemaps', '0', '0', 'Google Maps, View maps and directions.', '0', 'http://maps.google.com/maps?*\nhttp://maps.google.com/?*\nhttp://maps.google.com/maps/ms?*', '28416', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('109', '0', '1303850463', '1303850463', '0', 'Craigslist', 'craigslist', '0', '0', 'Craigslist is a centralized network of online communities, featuring free online classified advertisements - with sections devoted to jobs, housing, personals, for sale, services, community, gigs, resumes, and discussion forums.', '0', 'http://*.craigslist.org/*/*', '28672', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('110', '0', '1303851378', '1303850463', '0', 'My Opera', 'myopera', '0', '0', 'My Opera is a blog and photo sharing community with millions of members.', '0', 'http://my.opera.com/*/albums/show.dml?id=*\r\nhttp://my.opera.com/*/albums/showpic.dml?album=*&picture=*', '28928', 'http://my.opera.com/service/oembed', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('111', '0', '1303850463', '1303850463', '0', 'Tumblr', 'tumblr', '0', '0', 'Tumblr lets you effortlessly share anything. Post text, photos, quotes, links, music, and videos, from your browser, phone, desktop, email, or wherever you happen to be. You can customize everything, from colors, to your theme\'s HTML.', '0', 'http://tumblr.com/*\nhttp://*.tumblr.com/post/*', '29184', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('112', '0', '1303851340', '1303850463', '0', 'PollEverywhere', 'polleverywhere', '0', '0', 'Inexpensive Audience Response System that uses audience mobile phones or the web. Features live, animated charts in PowerPoint and on the web', '0', 'http://www.polleverywhere.com/polls/*\r\nhttp://www.polleverywhere.com/multiple_choice_polls/*\r\nhttp://www.polleverywhere.com/free_text_polls/*', '29440', 'http://www.polleverywhere.com/services/oembed/', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('113', '0', '1303850463', '1303850463', '0', 'Quantcast', 'quantcast', '0', '0', 'Quantcast helps publishers of all sizes understand the composition of their audiences and attract higher advertising rates, and helps marketers and agencies find elusive online audiences wherever they might be.', '0', 'http://www.quantcast.com/wd:*\nhttp://www.quantcast.com/*', '29696', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('114', '0', '1303850463', '1303850463', '0', 'Compete.com', 'compete', '0', '0', 'Provides free information for every site on the Internet including site traffic history and competitive analytics.', '0', 'http://siteanalytics.compete.com/*', '29952', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('115', '0', '1303850463', '1303850463', '0', 'StatSheet', 'statsheet', '0', '0', 'StatSheet is a sports media company focused on presenting stats and sports content in interesting and unique ways. Instead of relying on human-generated editorial or blog content, we build technology that allows fans to interact with and consume custom content targeted at the teams and athletes they care most about.', '0', 'http://statsheet.com/statplot/charts/*/*/*/*\nhttp://statsheet.com/statplot/charts/e/*\nhttp://statsheet.com/*/teams/*/*\nhttp://statsheet.com/tools/chartlets?chart=*', '30208', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('116', '0', '1303850463', '1303850463', '0', 'StatusNet', 'statusnet', '0', '0', 'StatusNet is the open source microblogging platform that helps you share and connect in real-time within your own domain.', '0', 'http://*.status.net/notice/*', '30464', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('117', '0', '1303850463', '1303850463', '0', 'Identi.ca', 'identica', '0', '0', 'Identi.ca, a micro-blogging service based on the Free Software StatusNet tool.', '0', 'http://identi.ca/notice/*', '30720', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('118', '0', '1303850463', '1303850463', '0', 'Brainbird', 'brainbird', '0', '0', 'Brainbird, a micro-blogging service based on the Free Software StatusNet tool.', '0', 'http://brainbird.net/notice/*', '30976', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('119', '0', '1303850463', '1303850463', '0', 'ShitMyDadSays', 'shitmydadsays', '0', '0', 'ShitMyDadSays, a micro-blogging service based on the Free Software StatusNet tool.', '0', 'http://shitmydadsays.com/notice/*', '31232', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('120', '0', '1303850463', '1303850463', '0', 'VZ Networks', 'vznetworks', '0', '0', 'VZ Networks is a popular German social networking platform containing three networks StudiVZ.net (college students), MeinVZ.net (non-students) and SchuelerVZ.net (high school students).', '0', 'http://www.studivz.net/Profile/*\nhttp://www.studivz.net/l/*\nhttp://www.studivz.net/Groups/Overview/*\nhttp://www.studivz.net/Gadgets/Info/*\nhttp://www.studivz.net/Gadgets/Install/*\nhttp://www.studivz.net/*\nhttp://www.meinvz.net/Profile/*\nhttp://www.meinvz.net/l/*\nhttp://www.meinvz.net/Groups/Overview/*\nhttp://www.meinvz.net/Gadgets/Info/*\nhttp://www.meinvz.net/Gadgets/Install/*\nhttp://www.meinvz.net/*\nhttp://www.schuelervz.net/Profile/*\nhttp://www.schuelervz.net/l/*\nhttp://www.schuelervz.net/Groups/Overview/*\nhttp://www.schuelervz.net/Gadgets/Info/*\nhttp://www.schuelervz.net/Gadgets/Install/*\nhttp://www.schuelervz.net/*', '31488', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('121', '0', '1303850463', '1303850463', '0', 'Myloc.me', 'mylocme', '0', '0', 'Myloc.me is the GPS location of any of your tweets sent through UberTwitter, Twitter clients for mobile devices.', '0', 'http://myloc.me/*', '31744', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('122', '0', '1303850463', '1303850463', '0', 'Pastebin.com', 'pastebin', '0', '0', 'Pastebin.com is a website where you can store text for a certain period of time.', '0', 'http://pastebin.com/*', '32000', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('123', '0', '1303850463', '1303850463', '0', 'Pastie', 'pastie', '0', '0', 'Pastie is one of the coolest paste apps ever.', '0', 'http://pastie.org/*\nhttp://www.pastie.org/*', '32256', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('124', '0', '1303850463', '1303850463', '0', 'Redux', 'redux', '0', '0', 'Redux is all about delivering the best personalized entertainment on the web. Redux taps into users\' friends and people that share their interests to deliver a uniquely addictive entertainment experience.', '0', 'http://redux.com/stream/item/*/*\nhttp://redux.com/f/*/*\nhttp://www.redux.com/stream/item/*/*\nhttp://www.redux.com/f/*/*', '32512', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('125', '0', '1303850463', '1303850463', '0', 'CloudApp', 'cloudapp', '0', '0', 'CloudApp allows you to share images, links, music, videos and files. Here is how it works: choose a file, drag it to the menubar and let us take care of the rest.', '0', 'http://cl.ly/*\nhttp://cl.ly/*/content', '32768', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('126', '0', '1303850463', '1303850463', '0', 'Speaker Deck', 'speakerdeck', '0', '0', 'Speaker Deck, a service to share presentations', '0', 'http://speakerdeck.com/u/*/p/*', '33024', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('127', '0', '1303850463', '1303850463', '0', 'Kiva', 'kiva', '0', '0', 'Kiva\'s mission is to connect people, through lending, for the sake of alleviating poverty.', '0', 'http://www.kiva.org/lend/*', '33280', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('128', '0', '1303850463', '1303850463', '0', 'Timetoast', 'timetoast', '0', '0', 'Timetoast allows people to create interactive timelines, which they can share anywhere on the web.', '0', 'http://www.timetoast.com/timelines/*', '33536', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('129', '0', '1303850463', '1303850463', '0', 'Storify', 'storify', '0', '0', 'Storify is a way to tell stories using social media such as Tweets, photos and videos.', '0', 'http://storify.com/*/*', '33792', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('130', '0', '1303850463', '1303850463', '0', 'Meetup', 'meetup', '0', '0', 'Meetup is the world\'s largest network of local groups.', '0', 'http://*meetup.com/*\nhttp://meetu.ps/*', '34048', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('131', '0', '1303850463', '1303850463', '0', 'dailymile', 'dailymile', '0', '0', 'dailymile is the easiest way to share your training with friends and stay motivated.', '0', 'http://www.dailymile.com/people/*/entries/*', '34304', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('132', '0', '1304769218', '1303850463', '0', 'Kinomap', 'kinomap', '0', '0', 'Share and explore your videos on a map.', '0', 'http://*.kinomap.com/*', '34560', 'http://www.kinomap.com/oembed', '1', '0', NULL, '1,220');
INSERT INTO tx_mediaoembed_provider VALUES ('133', '0', '1303850463', '1303850463', '0', 'MetaCDN', 'metacdn', '0', '0', 'MetaCDN is a cloud-based content delivery network (CDN) that harnesses high performance, low cost cloud storage networks. MetaCDN dramatically improves the performance of your website by replicating your content in over seventy locations around the world.', '0', 'http://www.metacdn.com/api/users/*/content/*\nhttp://www.metacdn.com/api/users/*/media/*', '34816', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('134', '0', '1303850463', '1303850463', '0', 'Prezi', 'prezi', '0', '0', 'Create astonishing presentations live and on the web.', '0', 'http://prezi.com/*/*', '35072', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('135', '0', '1303850463', '1303850463', '0', 'UserVoice', 'uservoice', '0', '0', 'Feedback and suggestions for your users.', '0', 'http://*.uservoice.com/*/suggestions/*', '35328', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('136', '0', '1303850463', '1303850463', '0', 'Formspring', 'formspring', '0', '0', 'Formspring is a community of millions of people connected by one simple thing: curiosity about one another. Ask, Answer and learn about your friends.', '0', 'http://formspring.me/*\nhttp://www.formspring.me/*\nhttp://formspring.me/*/q/*\nhttp://www.formspring.me/*/q/*', '35584', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('137', '0', '1303850463', '1303850463', '0', 'TwitLonger', 'twitlonger', '0', '0', 'Twitlonger is a way to let you post to Twitter when 140 characters just isn\'t enough.', '0', 'http://twitlonger.com/show/*\nhttp://www.twitlonger.com/show/*\nhttp://tl.gd/*', '35840', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('138', '0', '1303850463', '1303850463', '0', 'Qwiki', 'qwiki', '0', '0', 'Qwiki\'s goal is to forever improve the way people experience information', '0', 'http://www.qwiki.com/q/*', '36096', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('139', '0', '1303850463', '1303850463', '0', 'crocodoc', 'crocodoc', '0', '0', 'crocodoc allows you to collaboratively highlight and comment on PDFs, Word documents, images, and more.', '0', 'http://crocodoc.com/*\nhttp://*.crocodoc.com/*\nhttps://crocodoc.com/*\nhttps://*.crocodoc.com/*', '36352', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('140', '0', '1304769846', '1303850463', '0', 'Yfrog', 'yfrog', '0', '0', 'yfrog is a service run by ImageShack that lets you share your photos on and videos on Twitter.', '0', 'http://*yfrog.*/*', '36608', 'http://www.yfrog.com/api/oembed', '1', '0', NULL, '1,220');
INSERT INTO tx_mediaoembed_provider VALUES ('141', '0', '1303850463', '1303850463', '0', 'TweetPhoto', 'tweetphoto', '0', '0', 'TweetPhoto is a photo sharing platform for the real-time web. The service allows users to share photos on Twitter, Facebook and through favorite desktop and mobile clients. ', '0', 'http://tweetphoto.com/*', '36864', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('142', '0', '1304769158', '1303850463', '0', 'Flickr', 'flickr', '0', '0', 'Flickr is an image and video hosting website, web services suite, and online community', '0', 'http://*.flickr.com/photos/*\r\nhttp://flic.kr/*', '37120', 'http://www.flickr.com/services/oembed/', '1', '0', NULL, '1,220');
INSERT INTO tx_mediaoembed_provider VALUES ('143', '0', '1304769588', '1303850463', '0', 'TwitPic', 'twitpic', '0', '0', 'TwitPic lets you share photos on Twitter', '0', 'http://twitpic.com/*\r\nhttp://www.twitpic.com/*\r\nhttp://twitpic.com/photos/*\r\nhttp://www.twitpic.com/photos/*\r\nhttp://*.twitpic.com/*', '37376', '', '1', '0', NULL, '1,220');
INSERT INTO tx_mediaoembed_provider VALUES ('144', '0', '1303850463', '1303850463', '0', 'Imgur', 'imgur', '0', '0', 'Imgur makes sharing images with the Internet easy. It can be used to share pictures with friends, as well as post images on message boards and blogs. You can manipulate the image a number of ways and automatically submit it to popular sites such as reddit or digg. You can also view popular user-submitted images in the gallery. Best of all, Imgur is completely free. ', '0', 'http://*imgur.com/*', '37632', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('145', '0', '1303850463', '1303850463', '0', 'Posterous', 'posterous', '0', '0', 'Posterous is the dead simple way to put anything online using email.', '0', 'http://*.posterous.com/*\nhttp://post.ly/*', '37888', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('146', '0', '1303850463', '1303850463', '0', 'TwitGoo', 'twitgoo', '0', '0', 'Twitgoo is a quick, easy, reliable, and safe way to share images for Twitter.', '0', 'http://twitgoo.com/*', '38144', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('147', '0', '1304769463', '1303850463', '0', 'Photobucket', 'photobucket', '0', '0', 'Photobucket is the premier site on the Internet for uploading, sharing, linking and finding photos, videos and graphics. Your free Photobucket account can store thousands of photos and hours of video.', '0', 'http://i*.photobucket.com/albums/*\r\nhttp://s*.photobucket.com/albums/*\r\nhttp://*.photobucket.com/albums/*\r\nhttp://*.photobucket.com/groups/*', '38400', 'http://photobucket.com/oembed', '1', '0', NULL, '1,220');
INSERT INTO tx_mediaoembed_provider VALUES ('148', '0', '1304769368', '1303850463', '0', 'Phodroid', 'phodroid', '0', '0', 'Phodroid - the exclusive photo hosting service for Twidroid users.', '0', 'http://phodroid.com/*/*/*\r\nhttp://*.phodroid.com/*/*/*', '38656', '', '1', '0', NULL, '1,220');
INSERT INTO tx_mediaoembed_provider VALUES ('149', '0', '1303850463', '1303850463', '0', 'Mobypicture', 'mobypicture', '0', '0', 'Mobypicture - Share your mobile adventures directly with one click to Twitter, Flickr, Netvibes, Tumblr and many, many other social platforms', '0', 'http://www.mobypicture.com/user/*/view/*\nhttp://moby.to/*', '38912', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('150', '0', '1304769818', '1303850463', '0', 'xkcd', 'xkcd', '0', '0', 'A webcomic of romance, sarcasm, math, and language.', '0', 'http://xkcd.com/*\r\nhttp://www.xkcd.com/*\r\nhttp://imgs.xkcd.com/*\r\nhttp://*.xkcd.com/*/', '39168', '', '1', '0', NULL, '1,220');
INSERT INTO tx_mediaoembed_provider VALUES ('151', '0', '1303850687', '1303850463', '0', 'A Softer World', 'asofterworld', '0', '0', 'A Softer World is a comic that was created by Emily Horne and Joey Comeau so that people would recognize them as important artistic geniuses. Sometimes the "comic" is sad or harsh. It should be noted that this is in the tradition of George Simenon\'s \'romans durs\' (or \'hard novels\') and not in the lesser traditions of comics like Peanuts or anything else not French.', '0', 'http://www.asofterworld.com/index.php?id=*\nhttp://www.asofterworld.com/*.jpg\nhttp://asofterworld.com/*.jpg', '39424', 'http://www.nfb.ca/remote/services/oembed/', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('152', '0', '1303850463', '1303850463', '0', 'Dinosaur Comics', 'dinosaurcomics', '0', '0', 'Dinosaur Comics is a comic about talking dinosaurs! It appears online and also in print in some newspapers and magazines!', '0', 'http://www.qwantz.com/index.php?comic=*', '39680', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('153', '0', '1303850463', '1303850463', '0', '23', '23hq', '0', '0', '23 is the visual sharing company. Keep all your photos in one safe place. With 23 you can organise the photos, share them with anyone you want, and you can even order real prints of your digital photos.', '0', 'http://23hq.com/*/photo/*\nhttp://www.23hq.com/*/photo/*', '39936', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('154', '0', '1303850463', '1303850463', '0', 'Dribbble', 'dribbble', '0', '0', 'Dribbble is show and tell for designers, developers and other creatives. Share sneak peeks of your work as "shots" -- small screenshots of the designs and applications you\'re working on.', '0', 'http://*dribbble.com/shots/*\nhttp://drbl.in/*', '40192', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('155', '0', '1303850463', '1303850463', '0', 'SmugMug', 'smugmug', '0', '0', 'The ultimate in photo & video sharing. Easily create online photo albums. Share, store, organize and print.', '0', 'http://*.smugmug.com/*\nhttp://*.smugmug.com/*#*', '40448', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('156', '0', '1303850463', '1303850463', '0', 'Ember', 'emberapp', '0', '0', 'Ember is the best way to share your design inspiration with the world - from webpages to screenshots, design to illustration, Ember is built for creatives looking to build an online design scrapbook.', '0', 'http://emberapp.com/*/images/*\nhttp://emberapp.com/*/images/*/sizes/*\nhttp://emberapp.com/*/collections/*/*\nhttp://emberapp.com/*/categories/*/*/*\nhttp://embr.it/*', '40704', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('157', '0', '1303850463', '1303850463', '0', 'Picasa', 'picasa', '0', '0', 'Fast and easy photo sharing from Google. Share with friends and family, or explore public photos.', '0', 'http://picasaweb.google.com*/*/*#*\nhttp://picasaweb.google.com*/lh/photo/*\nhttp://picasaweb.google.com*/*/*', '40960', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('158', '0', '1303850463', '1303850463', '0', 'DailyBooth', 'dailybooth', '0', '0', 'Document and share your life with others. Get real time updates on what your friends and family are doing every day.', '0', 'http://dailybooth.com/*/*', '41216', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('159', '0', '1303850463', '1303850463', '0', 'Brizzly', 'brizzly', '0', '0', 'Brizzly / A simple way to experience the social web.', '0', 'http://brizzly.com/pic/*\nhttp://pics.brizzly.com/*.jpg', '41472', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('160', '0', '1303850463', '1303850463', '0', 'Img.ly', 'imgly', '0', '0', 'img.ly is a photo sharing service for twitter. Less characters, more user experience, that\'s it!.', '0', 'http://img.ly/*', '41728', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('161', '0', '1303850463', '1303850463', '0', 'Tinypic', 'tinypic', '0', '0', 'Tinypic is a fast, simple and reliable video and image hosting site that you can use to share your experiences.', '0', 'http://www.tinypic.com/view.php*\nhttp://tinypic.com/view.php*\nhttp://www.tinypic.com/player.php*\nhttp://tinypic.com/player.php*\nhttp://www.tinypic.com/r/*/*\nhttp://tinypic.com/r/*/*\nhttp://*.tinypic.com/*.jpg\nhttp://*.tinypic.com/*.png', '41984', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('162', '0', '1303850463', '1303850463', '0', 'meadd', 'meadd', '0', '0', 'Flog 5 photos per day, unlimited comments, unlimited titled images and more.', '0', 'http://meadd.com/*/*\nhttp://meadd.com/*', '42240', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('163', '0', '1303850463', '1303850463', '0', 'deviantART', 'deviantart', '0', '0', 'deviantART: where ART meets application!', '0', 'http://*.deviantart.com/art/*\nhttp://*.deviantart.com/gallery/*\nhttp://*.deviantart.com/#/*\nhttp://fav.me/*\nhttp://*.deviantart.com\nhttp://*.deviantart.com/gallery\nhttp://*.deviantart.com/*/*.jpg\nhttp://*.deviantart.com/*/*.gif\nhttp://*.deviantart.net/*/*.jpg\nhttp://*.deviantart.net/*/*.gif', '42496', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('164', '0', '1303850463', '1303850463', '0', 'Plixi', 'plixi', '0', '0', 'Plixi, formerly TweetPhoto, is a service for sharing pictures around people, places and events and creating collective memories. Plixi allows users to instantly share their photos to popular social networks through mobile devices and on the web.', '0', 'http://plixi.com/p/*\nhttp://plixi.com/profile/home/*\nhttp://plixi.com/*\nhttp://m.plixi.com/*', '42752', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('165', '0', '1303850463', '1303850463', '0', 'fotopedia', 'fotopedia', '0', '0', 'Fotopedia is breathing new life into photos by building a photo encyclopedia that lets photographers and photo enthusiasts collaborate and enrich images to be useful for the whole world wide web.', '0', 'http://www.fotopedia.com/*/*\nhttp://fotopedia.com/*/*', '43008', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('166', '0', '1303850463', '1303850463', '0', 'photozou', 'photozou', '0', '0', 'Photozou, is a Japanese photo sharing site for social media.', '0', 'http://photozou.jp/photo/show/*/*\nhttp://photozou.jp/photo/photo_only/*/*', '43264', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('167', '0', '1303850463', '1303850463', '0', 'instagram', 'instagram', '0', '0', 'Instagram, a fun & quirky way to share your life with friends through a series of pictures. Snap a photo, then choose a filter to transform the look and feel of the shot into a memory to keep around forever.', '0', 'http://instagr.am/p/*\nhttp://instagram.com/p/*', '43520', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('168', '0', '1303850463', '1303850463', '0', 'Skitch', 'skitch', '0', '0', 'Skitch.com is a webservice that works hand in hand with our application Skitch to give you 1-click uploading of images for fast and fun image sharing.', '0', 'http://skitch.com/*/*/*\nhttp://img.skitch.com/*\nhttps://skitch.com/*/*/*\nhttps://img.skitch.com/*', '43776', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('169', '0', '1303850463', '1303850463', '0', 'Ovi', 'ovi', '0', '0', 'Share photos and videos. Anytime. Anywhere.', '0', 'http://share.ovi.com/media/*/*', '44032', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('170', '0', '1303850463', '1303850463', '0', 'Questionable Content', 'questionablecontent', '0', '0', 'Questionable Content (or "QC," as it is frequently abbreviated) is an online comic strip that is ostensibly about romance, indie rock, little robots, and the problems people have.', '0', 'http://www.questionablecontent.net/\nhttp://questionablecontent.net/\nhttp://www.questionablecontent.net/view.php*\nhttp://questionablecontent.net/view.php*\nhttp://questionablecontent.net/comics/*.png\nhttp://www.questionablecontent.net/comics/*.png', '44288', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('171', '0', '1303850463', '1303850463', '0', 'picplz', 'picplz', '0', '0', 'picplz is the easiest way to share pictures from your iPhone or Android device', '0', 'http://picplz.com/user/*/pic/*/', '44544', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('172', '0', '1303850463', '1303850463', '0', 'TwitrPix', 'twitrpix', '0', '0', 'Social photo sharing site.', '0', 'http://twitrpix.com/*\nhttp://*.twitrpix.com/*', '44800', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('173', '0', '1303850463', '1303850463', '0', 'someecards', 'someecards', '0', '0', 'Someecards may or may not be the greatest thing since ecards. It was created by Brook Lundy and Duncan Mitchell and a dollar and a half-assed dream.', '0', 'http://www.someecards.com/*/*\nhttp://someecards.com/*/*\nhttp://some.ly/*\nhttp://www.some.ly/*', '45056', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('174', '0', '1303850463', '1303850463', '0', 'pikchur', 'pikchur', '0', '0', 'Pikchur is a simple service that updates your social networks / micro-blogging platforms with pictures & videos (Motion Pikchurs)! No need to signup! Just login with one of our many supported platforms and start sending your Piks today!', '0', 'http://pikchur.com/*', '45312', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('175', '0', '1303850463', '1303850463', '0', 'Achewood', 'achewood', '0', '0', 'Achewood is a webcomic created by Chris Onstad in 2001. It portrays the lives of a group of anthropomorphic stuffed toys, robots, and pets. Many of the characters live together in the home of their owner, Chris, at the fictional address of 62 Achewood Court.', '0', 'http://achewood.com/*\nhttp://www.achewood.com/*\nhttp://achewood.com/index.php*\nhttp://www.achewood.com/index.php*', '45568', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('176', '0', '1303850463', '1303850463', '0', 'WhoSay', 'whosay', '0', '0', 'WhoSay is a service that helps artists, athletes and iconic personalities connect with their fans.', '0', 'http://www.whosay.com/content/*\nhttp://www.whosay.com/photos/*\nhttp://www.whosay.com/videos/*\nhttp://say.ly/*', '45824', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('177', '0', '1303850463', '1303850463', '0', 'Ow.ly', 'owly', '0', '0', 'Ow.ly - Shorten urls, share files and track visits', '0', 'http://ow.ly/i/*', '46080', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('178', '0', '1303850463', '1303850463', '0', 'Color', 'color', '0', '0', 'Simultaneously use multiple iPhones and Androids to capture photos, videos, and conversations into a group album.', '0', 'http://color.com/s/*', '46336', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('179', '0', '1303850463', '1303850463', '0', 'Bnter', 'bnter', '0', '0', 'Bnter is a way to share your conversations and learn more about the lives of friends and others.', '0', 'http://bnter.com/convo/*', '46592', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('180', '0', '1304768614', '1303850463', '0', 'Amazon', 'amazon', '0', '0', 'Amazon.com is a leading global Internet company and one of the most trafficked Internet retail destinations worldwide. Amazon directly sells, or acts as a platform for the sale of, a very broad range of products, including books, music, videos, consumer electronics, clothing and household products.', '0', 'http://*amazon.*/gp/product/*\r\nhttp://*amazon.*/*/dp/*\r\nhttp://*amazon.*/dp/*\r\nhttp://*amazon.*/o/ASIN/*\r\nhttp://*amazon.*/gp/offer-listing/*\r\nhttp://*amazon.*/*/ASIN/*\r\nhttp://*amazon.*/gp/product/images/*\r\nhttp://*amazon.*/gp/aw/d/*\r\nhttp://www.amzn.com/*\r\nhttp://amzn.com/*', '46848', '', '1', '0', NULL, '1,220');
INSERT INTO tx_mediaoembed_provider VALUES ('181', '0', '1303850463', '1303850463', '0', 'ShopStyle', 'shopstyle', '0', '0', 'ShopStyle is the online equivalent of browsing the aisles of the world\'s most fabulous store.', '0', 'http://www.shopstyle.com/browse*\nhttp://www.shopstyle.com/action/apiVisitRetailer*\nhttp://api.shopstyle.com/action/apiVisitRetailer*\nhttp://www.shopstyle.com/action/viewLook*', '47104', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('182', '0', '1303850463', '1303850463', '0', 'SoundCloud', 'soundcloud', '0', '0', 'SoundCloud lets you move music fast &amp; easy. The platform takes the daily hassle out of receiving, sending &amp; distributing music for artists, record labels &amp; other music professionals.', '0', 'http://soundcloud.com/*\nhttp://soundcloud.com/*/*\nhttp://soundcloud.com/*/sets/*\nhttp://soundcloud.com/groups/*\nhttp://snd.sc/*', '47360', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('183', '0', '1303850463', '1303850463', '0', 'Last.fm', 'lastfm', '0', '0', 'Last.fm - Listen to free music with internet radio and the largest music catalogue online.', '0', 'http://www.last.fm/music/*\nhttp://www.last.fm/music/+videos/*\nhttp://www.last.fm/music/+images/*\nhttp://www.last.fm/music/*/_/*\nhttp://www.last.fm/music/*/*', '47616', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('184', '0', '1303850463', '1303850463', '0', 'Mixcloud', 'mixcloud', '0', '0', 'Mixcloud is re-thinking radio. Listen to great radio shows, Podcasts and DJ mix sets on-demand. Upload and promote your own Cloudcast for free.', '0', 'http://www.mixcloud.com/*/*/', '47872', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('185', '0', '1303850463', '1303850463', '0', 'Radionomy', 'radionomy', '0', '0', 'Radionomy, everyone can finally create his radio on the Net! It\'s all so easy. By browsing through our vast music and content libraries. By integrating one\'s musical creations or excerpts from one\'s record library. And one\'s own audio content, sequences, reportages.', '0', 'http://www.radionomy.com/*/radio/*\nhttp://radionomy.com/*/radio/*', '48128', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('186', '0', '1303850463', '1303850463', '0', 'Hark', 'hark', '0', '0', 'Hark is an Internet media company that is changing the way people express themselves through creating, sharing and listening to entertaining, informative and timely sound bites online and through mobile devices.', '0', 'http://www.hark.com/clips/*', '48384', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('187', '0', '1303850463', '1303850463', '0', 'Rdio', 'rdio', '0', '0', 'Unlimited Music. Everywhere. Choose the music you want to play and listen as much as you want - from the web or your phone, even when you\'re offline.', '0', 'http://www.rdio.com/#/artist/*/album/*\nhttp://www.rdio.com/artist/*/album/*', '48640', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('188', '0', '1303850463', '1303850463', '0', 'zero\'\'', 'zeroinch', '0', '0', 'zero\'\' [speak: zero inch] is a specialised digital record store featuring electronic music and other related styles. They are based in Vienna and Berlin.', '0', 'http://www.zero-inch.com/*', '48896', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('189', '0', '1303850463', '1303850463', '0', 'Band Camp', 'bandcamp', '0', '0', 'Bandcamp is an online music store, as well as a platform for artist promotion, that caters mainly for independent artists.', '0', 'http://*.bandcamp.com/\nhttp://*.bandcamp.com/track/*\nhttp://*.bandcamp.com/album/*', '49152', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('190', '0', '1303850463', '1303850463', '0', 'Free Music Archive', 'freemusicarchive', '0', '0', 'The Free Music Archive is an interactive library of high-quality, legal audio downloads. The Free Music Archive is directed by WFMU, the most renowned freeform radio station in America.', '0', 'http://freemusicarchive.org/music/*\nhttp://www.freemusicarchive.org/music/*\nhttp://freemusicarchive.org/curator/*\nhttp://www.freemusicarchive.org/curator/*', '49408', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('191', '0', '1303850463', '1303850463', '0', 'NPR', 'npr', '0', '0', 'A thriving media organization at the forefront of digital innovation, NPR creates and distributes award-winning news, information, and music programming to a network of 900 independent stations. Through them, NPR programming reaches 27.2 million listeners every week.', '0', 'http://www.npr.org/*/*/*/*/*\nhttp://www.npr.org/*/*/*/*/*/*\nhttp://www.npr.org/*/*/*/*/*/*/*\nhttp://www.npr.org/templates/story/story.php*', '49664', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('192', '0', '1303850463', '1303850463', '0', 'Huffduffer', 'huffduffer', '0', '0', 'Create your own podcast: find links to audio files on the Web; huffduff the links (add them to your podcast); subscribe to podcasts of other found sounds.', '0', 'http://huffduffer.com/*/*', '49920', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('193', '0', '1303850463', '1303850463', '0', 'AudioBoo', 'audioboo', '0', '0', 'A mobile and web platform that effortlessly allows you to record and upload audio for your friends, family or the rest of the world to hear.', '0', 'http://www.audioboo.fm/boos/*\nhttp://audioboo.fm/boos/*\nhttp://boo.fm/b*', '50176', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('194', '0', '1303850463', '1303850463', '0', 'xiami', 'xiami', '0', '0', 'Xiami is one of the largest music providers in China, on Xiami you can search with friends and share your favorite music.', '0', 'http://www.xiami.com/song/*\nhttp://xiami.com/song/*', '50432', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('195', '0', '1303850463', '1303850463', '0', 'SayNow', 'saynow', '0', '0', 'SayNow set out to build voice-based experiences that are fun and social. Along the way, we reinvented the way phone calls are made today. Voice is engaging, authentic, and an emotional form of communication, yet is largely ignored on social media and smartphone platforms.', '0', 'http://www.saynow.com/playMsg.html*\nhttp://www.saynow.com/playMsg.html*', '50688', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('196', '0', '1303850463', '1303850463', '0', 'Grooveshark', 'grooveshark', '0', '0', 'Grooveshark is an internationally available online music search engine, music streaming service and music recommendation web software application, allowing users to search for, stream, and upload music free of charge that can be played immediately or added to a playlist.', '0', 'http://listen.grooveshark.com/s/*', '50944', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('197', '0', '1303850463', '1303850463', '0', 'RadioReddit', 'radioreddit', '0', '0', 'radioreddit.com is the source for quality new and popular independent music.', '0', 'http://radioreddit.com/songs*\nhttp://www.radioreddit.com/songs*\nhttp://radioreddit.com/?q=songs*\nhttp://www.radioreddit.com/?q=songs*', '51200', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('198', '0', '1303850463', '1303850463', '0', 'gogoyoko', 'gogoyoko', '0', '0', 'gogoyoko is a social music marketplace where music fans can buy directly from the artists.', '0', 'http://www.gogoyoko.com/song/*', '51456', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('199', '0', '1303850463', '1303850463', '0', 'ESPN', 'espn', '0', '0', 'ESPN.com provides comprehensive sports coverage.  Complete sports information including NFL, MLB, NBA, College Football, College Basketball scores and news.', '0', 'http://espn.go.com/video/clip*\nhttp://espn.go.com/*/story*', '51712', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('200', '0', '1303850463', '1303850463', '0', 'ABC News', 'abcnews', '0', '0', 'ABC News brings you the latest  breaking world news, national news, political, business and entertainment news, as well as stories from 60 Minutes and the Early Show.', '0', 'http://abcnews.com/*/video/*\nhttp://abcnews.com/video/playerIndex*', '51968', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('201', '0', '1303850463', '1303850463', '0', 'Washington Post', 'washingtonpost', '0', '0', 'Washington Post Digital brings Washington to the world and the world to Washington.', '0', 'http://washingtonpost.com/wp-dyn/*/video/*/*/*/*\nhttp://www.washingtonpost.com/wp-dyn/*/video/*/*/*/*', '52224', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('202', '0', '1303850463', '1303850463', '0', 'Boston.com', 'boston', '0', '0', 'Boston.com is the exclusive online home of The Boston Globe. We take pride in our up-to-the minute news and features such as dynamic sports coverage, arts and entertainment, weather and traffic.', '0', 'http://www.boston.com/video*\nhttp://boston.com/video*', '52480', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('203', '0', '1303850463', '1303850463', '0', 'Facebook', 'facebook', '0', '0', 'Facebook helps you connect and share with the people in your life.', '0', 'http://www.facebook.com/photo.php*\nhttp://www.facebook.com/video/video.php*\nhttp://www.facebook.com/v/*', '52736', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('204', '0', '1303850463', '1303850463', '0', 'CNBC', 'cnbc', '0', '0', 'Find the latest stock market news, information &amp; headlines. Get up to date business news as well as stock market, financial &amp; earnings news online. View world markets streaming charts &amp; video; find stock tickers and quotes on the official CNBC site.', '0', 'http://cnbc.com/id/*?*video*\nhttp://www.cnbc.com/id/*?*video*\nhttp://cnbc.com/id/*/play/1/video/*\nhttp://www.cnbc.com/id/*/play/1/video/*', '52992', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('205', '0', '1303850463', '1303850463', '0', 'CBS News', 'cbsnews', '0', '0', 'CBS News brings you the latest  breaking world news, national news, political, business and entertainment news, as well as stories from 60 Minutes and the Early Show.', '0', 'http://cbsnews.com/video/watch/*', '53248', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('206', '0', '1303850463', '1303850463', '0', 'Google Buzz', 'googlebuzz', '0', '0', 'Google Buzz is a new way to start conversations about the things you find interesting. Go beyond status messages. Share updates, photos, videos, and more. Start conversations about the things you find interesting.', '0', 'http://www.google.com/buzz/*/*/*\nhttp://www.google.com/buzz/*\nhttp://www.google.com/profiles/*\nhttp://google.com/buzz/*/*/*\nhttp://google.com/buzz/*\nhttp://google.com/profiles/*', '53504', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('207', '0', '1303850463', '1303850463', '0', 'CNN', 'cnn', '0', '0', 'CNN.com - Breaking News, U.S., World, Weather, Entertainment &amp; Video News', '0', 'http://www.cnn.com/video/*', '53760', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('208', '0', '1303850463', '1303850463', '0', 'CNN Edition', 'cnnedition', '0', '0', 'CNN.com International delivers breaking news from across the globe and information on the latest top stories, business, sports and entertainment headlines.  Follow the news as it happens through: special reports, videos, audio, photo galleries plus interactive maps and timelines.', '0', 'http://edition.cnn.com/video/*', '54016', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('209', '0', '1303850463', '1303850463', '0', 'CNN Money', 'cnnmoney', '0', '0', 'Business, financial, personal finance news - CNNMoney.com', '0', 'http://money.cnn.com/video/*', '54272', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('210', '0', '1303850463', '1303850463', '0', 'MSNBC', 'msnbc', '0', '0', 'Breaking News, Weather, Business, Health, Entertainment, Sports, Politics, Travel, Science, Technology, Local, US &amp; World News- msnbc.com', '0', 'http://today.msnbc.msn.com/id/*/vp/*\nhttp://www.msnbc.msn.com/id/*/vp/*\nhttp://www.msnbc.msn.com/id/*/ns/*\nhttp://today.msnbc.msn.com/id/*/ns/*', '54528', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('211', '0', '1303850463', '1303850463', '0', 'Fox Sports', 'foxsports', '0', '0', 'FOX Sports on MSN - Sports News, Videos, Scores, Teams, Fantasy', '0', 'http://multimedia.foxsports.com/m/video/*/*\nhttp://msn.foxsports.com/video*', '54784', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('212', '0', '1303850463', '1303850463', '0', 'Global Post', 'globalpost', '0', '0', 'GlobalPost has been one of the leaders in the movement to create new, more sustainable models for journalism at a time when news organizations everywhere are struggling with historic forces of change driven by technology, new consumer habits, and an eroding economic support system for traditional media.', '0', 'http://www.globalpost.com/video/*\nhttp://www.globalpost.com/dispatch/*', '55040', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('213', '0', '1303850463', '1303850463', '0', 'The Guardian', 'guardian', '0', '0', 'Guardian, a British national newspaper with the world\'s leading liberal voice. Find your Latest news, sport, business, comment, analysis and reviews.', '0', 'http://guardian.co.uk/*/video/*/*/*/*\nhttp://www.guardian.co.uk/*/video/*/*/*/*', '55296', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('214', '0', '1303850463', '1303850463', '0', 'Bravo Tv', 'bravotv', '0', '0', 'Bravo Tv - includes shows Top Chef, My Life on the D-List, the hit series Shear Genius, Million Dollar Listing, The Millionaire Matchmaker, Tim Gunn\'s Guide to Style, Make Me A Supermodel, and the water cooler sensations that are The Real Housewives.', '0', 'http://bravotv.com/*/*/videos/*\nhttp://www.bravotv.com/*/*/videos/*', '55552', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('215', '0', '1303850463', '1303850463', '0', 'National Geographic', 'nationalgeographic', '0', '0', 'View hundreds of free videos from National Geographic, featuring animal videos, weather videos, nature videos, world music videos and other most popular video content including shark videos.', '0', 'http://video.nationalgeographic.com/*/*/*.html', '55808', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('216', '0', '1303850463', '1303850463', '0', 'Discovery Channel', 'discovery', '0', '0', 'Discovery Channel online lets you explore science, history, space, tech, sharks, &amp; more, with videos &amp; news, plus exclusives on your favorite TV shows.', '0', 'http://dsc.discovery.com/videos/*\nhttp://animal.discovery.com/videos/*\nhttp://health.discovery.com/videos/*\nhttp://investigation.discovery.com/videos/*\nhttp://military.discovery.com/videos/*\nhttp://planetgreen.discovery.com/videos/*\nhttp://science.discovery.com/videos/*\nhttp://tlc.discovery.com/videos/*', '56064', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('217', '0', '1303850463', '1303850463', '0', 'Forbes', 'forbes', '0', '0', 'Forbes.com Video Network - The leading source for reliable business news and financial information.', '0', 'http://video.forbes.com/fvn/*', '56320', '', '1', '0', NULL, '1');
INSERT INTO tx_mediaoembed_provider VALUES ('218', '0', '1304768803', '1303850687', '0', 'Dailymotion', '', '0', '1', NULL, '0', 'http://*.dailymotion.com/*', '1000000000', 'http://www.dailymotion.com/api/oembed/', NULL, '0', NULL, NULL);
INSERT INTO tx_mediaoembed_provider VALUES ('219', '0', '1304768838', '1303850688', '0', 'dotSUB.com', '', '0', '1', NULL, '0', 'http://dotsub.com/view/*', '1000000000', 'http://dotsub.com/services/oembed', NULL, '0', NULL, NULL);
INSERT INTO tx_mediaoembed_provider VALUES ('220', '0', '1303851288', '1303851288', '1', 'oohEmbed', '', '0', '0', 'oohEmbed is an oEmbed compatible provider of HTML embed codes for various web sites.', '0', '', '1024', 'http://oohembed.com/oohembed/', '', '1', NULL, NULL);
INSERT INTO tx_mediaoembed_provider VALUES ('221', '0', '1304769251', '1304769251', '1', 'LiveJournal UserPic', '', '0', '0', 'Avatar image for LiveJournal user. Uses http://ljpic.seacrow.com/', '0', 'http://*.livejournal.com/', '512', '', NULL, '0', NULL, '220');
INSERT INTO tx_mediaoembed_provider VALUES ('222', '0', '1304769743', '1304769743', '1', 'Wikipedia', '', '0', '0', 'Returns lead content from a Wikipedia page as \'html\' attribute of link type oEmbed response', '0', 'http://*.wikipedia.org/wiki/*', '256', '', NULL, '0', NULL, '220');
INSERT INTO tx_mediaoembed_provider VALUES ('223', '0', '1304769799', '1304769799', '1', 'Wordpress.com', '', '0', '0', 'Returns lead content from a Wordpress.com blog post page as \'html\' attribute of link type oEmbed response', '0', 'http://*.wordpress.com/*/*/*/*', '128', '', NULL, '0', NULL, '220');


