<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by Tx_Extbase_Utility_Extension::createAutoloadRegistryForExtension.
// This file was generated on 2011-04-21 22:34

$extensionClassesPath = t3lib_extMgm::extPath('mediaoembed') . 'Classes/';
return array(
	'tx_mediaoembed_exception_httpnotfoundexception' => $extensionClassesPath . 'Exception/HttpNotFoundException.php',
	'tx_mediaoembed_exception_httpnotimplementedexception' => $extensionClassesPath . 'Exception/HttpNotImplementedException.php',
	'tx_mediaoembed_exception_unauthorizedexception' => $extensionClassesPath . 'Exception/HttpUnauthorizedException.php',
	'tx_mediaoembed_exception_invalidresourcetypeexception' => $extensionClassesPath . 'Exception/InvalidResourceTypeException.php',
	'tx_mediaoembed_exception_invalidresponseexception' => $extensionClassesPath . 'Exception/InvalidResponseException.php',
	'tx_mediaoembed_exception_invalidurlexception' => $extensionClassesPath . 'Exception/InvalidUrlException.php',
	'tx_mediaoembed_exception_nomatchingproviderexception' => $extensionClassesPath . 'Exception/NoMatchingProviderException.php',
	'tx_mediaoembed_exception_oembedexception' => $extensionClassesPath . 'Exception/OEmbedException.php',
	'tx_mediaoembed_hooks_cmsmediaitems' => $extensionClassesPath . 'Hooks/CmsMediaitems.php',
	'tx_mediaoembed_request_httprequest' => $extensionClassesPath . 'Request/HttpRequest.php',
	'tx_mediaoembed_request_providerresolver' => $extensionClassesPath . 'Request/ProviderResolver.php',
	'tx_mediaoembed_request_requestbuilder' => $extensionClassesPath . 'Request/RequestBuilder.php',
	'tx_mediaoembed_response_abstractresponse' => $extensionClassesPath . 'Response/AbstractResponse.php',
	'tx_mediaoembed_response_linkresponse' => $extensionClassesPath . 'Response/LinkResponse.php',
	'tx_mediaoembed_response_photoresponse' => $extensionClassesPath . 'Response/PhotoResponse.php',
	'tx_mediaoembed_response_responsebuilder' => $extensionClassesPath . 'Response/ResponseBuilder.php',
	'tx_mediaoembed_response_richresponse' => $extensionClassesPath . 'Response/RichResponse.php',
	'tx_mediaoembed_response_videoresponse' => $extensionClassesPath . 'Response/VideoResponse.php',
);
?>